### ISSUE TITLE
Cannot launch any game

### ISSUE THREAD

**Issue by FeyrisTan** [Faugus/faugus-launcher#1]
`Exceptionignored in atexit callback: <function stop_scc_daemon at 0x7648e9216b60>
Traceback (most recent call last):
  File "/usr/bin/faugus-run", line 129, in stop_scc_daemon
    subprocess.run(["scc-daemon", "stop"], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scc-daemon'`

**Comment by Faugus** [comment]
What distribution are you running?

This error is not related to the game not running.
When the game process terminates, it stops the SC Controller service. If you're not using the SC Controller, it gives this error.
It doesn't affect the game.

Could you please post the full log?

**Comment by FeyrisTan** [comment]
Thats all the terminal spits out. 
Arch linux

**Comment by Faugus** [comment]
Shoud be something like this:

```
[faugus@archlinux ~]$ faugus-launcher
MANGOHUD=1 WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/world-of-warcraft GAMEID=world-of-warcraft "/usr/bin/umu-run" "/mnt/data/Games/World of Warcraft/_classic_era_/WowClassic.exe"
Exception ignored in atexit callback: <function stop_scc_daemon at 0x798adef1fce0>
Traceback (most recent call last):
  File "/usr/bin/faugus-run", line 129, in stop_scc_daemon
    subprocess.run(["scc-daemon", "stop"], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scc-daemon'
```

**Comment by FeyrisTan** [comment]
With your recent change I now get this:

`UMU-Proton is up to date
steamrt is up to date
Traceback (most recent call last):
  File "/usr/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 778, in main
    return run_command(command)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 641, in run_command
    gamescope_baselayer_sequence = get_gamescope_baselayer_order()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 511, in get_gamescope_baselayer_order
    d = display.Display(":0")
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.12/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'`

Maybe has something to do with xauth?
xauth info points to /run/user/1000/xauth_LkLysz

using wayland

**Comment by FeyrisTan** [comment]
runs fine under X11 but 2 days ago IT DID run with wayland.

**Comment by Faugus** [comment]
I can't reproduce this problem.
It runs fine on X11 or Wayland on Arch or Fedora.

Are you using gamescope?

**Comment by FeyrisTan** [comment]
> I can't reproduce this problem. It runs fine on X11 or Wayland on Arch or Fedora.
> 
> Are you using gamescope?

Nope

**Comment by Faugus** [comment]
I was able to get the same error using gamescope, but it doesn't prevent the game from being launched.

What game are you trying to run?

**Comment by FeyrisTan** [comment]
as stated above it happens with every game.
did a clean install just to check but it still occurs.

**Comment by FeyrisTan** [comment]
so running echo $DISPLAY returns 1 instead of 0.
in: /usr/lib/python3.12/site-packages/umu/umu_run.py
changing line 511 from d = display.Display(":0") to d = display.Display(":1") works

**Comment by Faugus** [comment]
https://github.com/Open-Wine-Components/umu-launcher/issues/145

Looks like it's a known bug.

**Comment by Faugus** [comment]
Not my bug

**Comment by FeyrisTan** [comment]
Sorry for not closing it. Thanks
