### ISSUE TITLE
Unable to Install via aur helper

### ISSUE THREAD

**Issue by DieALot36T9** [Faugus/faugus-launcher#10]
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 zenity-4.0.2-1.1-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn-1.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from at.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from nl-ams.soulharsh007.dev : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from aur.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.lesviallon.fr : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from no.mirror.cx : The requested URL :: Proceed with installation? [Y/n] 
:: Retrieving packages...
 zenity-4.0.2-1.1-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn-1.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from at.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from nl-ams.soulharsh007.dev : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from aur.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.lesviallon.fr : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from no.mirror.cx : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.truenetwork.ru : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn77.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from us.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mir.cachyos.fr : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.truenetwork.ru : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirror.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn77.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from us.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from cdn.cachyos.org : The requested URL returned error: 404
error: failed retrieving file 'zenity-4.0.2-1.1-x86_64.pkg.tar.zst' from mir.cachyos.fr : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

**Comment by Faugus** [comment]
Thanks for reporting.
I can't reproduce.
I just fresh installed CachyOS on a VM and it's working fine.
There's something wrong with your repositories.
Try to update your system with `sudo pacman -Syyu`.

**Comment by DieALot36T9** [comment]
fixed now somehow
