### ISSUE TITLE
resolve error

### ISSUE THREAD

**Issue by RaulKong898** [Faugus/faugus-launcher#11]
raulkong898@fedora:~$ sudo dnf -y install faugus-launcher
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
  - package faugus-launcher-1.0-76.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher requires umu-launcher, but none of the providers can be installed
  - package faugus-launcher-1.0-77.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher requires umu-launcher, but none of the providers can be installed
  - package faugus-launcher-1.1-1.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher requires umu-launcher, but none of the providers can be installed
  - package faugus-launcher-1.1-2.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher requires umu-launcher, but none of the providers can be installed
  - nothing provides python(abi) = 3.12 needed by umu-launcher-1.1.2-1.20241012.b34df64.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides python3.12dist(filelock) >= 3.9 needed by umu-launcher-1.1.2-1.20241012.b34df64.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides python3.12dist(python-xlib) >= 0.33 needed by umu-launcher-1.1.2-1.20241012.b34df64.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides python(abi) = 3.12 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides python3.12dist(filelock) >= 3.9 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides python3.12dist(python-xlib) >= 0.33 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
You can try to add to command line:
  --skip-broken to skip uninstallable packages

**Comment by Faugus** [comment]
Thanks for reporting.
I can't reproduce.
I have Fedora fresh installed in a VM and it installs just fine.
What distro are you running?

**Comment by RaulKong89** [comment]
distro fedora

**Comment by Faugus** [comment]
Please make sure your system is up to date.
`sudo dnf update -y --refresh`

**Comment by RaulKong89** [comment]
I tried and it doesn't go. It doesn't function.

**Comment by Faugus** [comment]
I just reinstalled Fedora on a VM and it's working fine.
There's something wrong with your system.
If you are using Fedora 40 and it's up to date, it should be pulling the dependencies.

**Comment by Faugus** [comment]
I just reinstalled Fedora on a VM and it's working fine.
There's something wrong with your system.
If you are using Fedora 40 and it's up to date, it should be pulling the dependencies.

**Comment by Onxr** [comment]
I am having similar issue

```
Operating System: Fedora Linux 42
KDE Plasma Version: 6.5.1
KDE Frameworks Version: 6.19.0
Qt Version: 6.9.3
Kernel Version: 6.17.7-200.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 16 GiB of RAM (15.5 GiB usable)
Graphics Processor: AMD Radeon RX 6700 XT
Product Name: B450M Steel Legend
```

```
sudo dnf -y copr enable faugus/faugus-launcher
sudo dnf -y install faugus-launcher
 https://copr.fedorainfracloud.org/api_3/rpmrepo/faugus/faugus-launcher 100% | 308.0   B/s | 361.0   B |  00m01s
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.
Updating and loading repositories:
 Copr repo for faugus-launcher owned by faugus                          100% |   1.4 KiB/s |   1.8 KiB |  00m01s
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides umu-launcher needed by faugus-launcher-1.9.7-1.fc42.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides umu-launcher needed by faugus-launcher-1.9.8-1.fc42.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
  - nothing provides umu-launcher needed by faugus-launcher-1.9.9-1.fc42.noarch from copr:copr.fedorainfracloud.org:faugus:faugus-launcher
You can try to add to command line:
  --skip-broken to skip uninstallable packages
```

**Comment by Faugus** [comment]
@Onxr Thanks for reporting.
Recently I removed the `umu-launcher` package from the repository and forgot to update the `faugus-launcher` package.
I just pushed a new release.
Please try again.

**Comment by Onxr** [comment]
> [@Onxr](https://github.com/Onxr) Thanks for reporting. Recently I removed the `umu-launcher` package from the repository and forgot to update the `faugus-launcher` package. I just pushed a new release. Please try again.

Yep it is fixed thanks
