### ISSUE TITLE
Do not hardcode XDG base directories and XDG user directories

### ISSUE THREAD

**Issue by nl6720** [Faugus/faugus-launcher#14]
faugus-launcher hardcodes the paths of [XDG base directories](https://wiki.archlinux.org/title/XDG_Base_Directory) like `~/.config` and `~/.local/share` and [XDG user directories](https://wiki.archlinux.org/title/XDG_user_directories) like `~/Desktop`.

This breaks things when using non-default XDG base directories (via environment variables) and when XDG user directories are using non-English names (since "`Desktop`" would have a localized name instead).

**Comment by Faugus** [comment]
Thanks for the feedback.
I did the changes.
Will be available on the next release.

**Comment by nl6720** [comment]
Thanks, but I don't think

https://github.com/Faugus/faugus-launcher/blob/f867fe5784c8c91a5231706d4d1933132005ef0c/faugus-launcher.py#L25

will work since XDG user directories are not configured via environment variables. They are set in `$XDG_CONFIG_HOME/user-dirs.dirs` or `/etc/xdg/user-dirs.defaults` instead.

**Comment by Faugus** [comment]
It should be fixed now.

**Comment by nl6720** [comment]
Thanks, it works now!
