### ISSUE TITLE
More verbose running window

### ISSUE THREAD

**Issue by bogdan-the-great** [Faugus/faugus-launcher#15]
A snippet from my first launch in terminal:
```
...
umu-launcher version 1.1.3 (3.11.10 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0])
Setting up Unified Launcher for Windows Games on Linux...
Downloading UMU-Proton-9.0-3.2.sha512sum...
Downloading UMU-Proton-9.0-3.2.tar.gz...
Downloading latest steamrt sniper, please wait...
UMU-Proton-9.0-3.2.tar.gz: SHA512 is OK
Extracting UMU-Proton-9.0-3.2.tar.gz...
...
```

Meanwhile in GUI:
```
Updating. Please wait...
```

I would appreciate more verbose output in GUI, because the first setup of everything can take a while and you don't really know if it hung up or still doing something. I mean something like:
```
Setting up UMU...
Downloading UMU-Proton... (or GE-Proton)
Downloading steamrt sniper...
Extracting UMU-Proton...
```
As the user won't care about the version of Proton for example.

Plus users will know what is the problem when stuck for 30 minutes on one step.

**Comment by Faugus** [comment]
Thanks for the feedback.
I did some changes do the verbose output.
The Flatpak is updated.
https://github.com/Faugus/faugus-launcher/releases/download/v1.1-3/faugus-launcher-0.1.1.flatpak

**Comment by marendowski** [comment]
I have one nitpick to make: Can there be only one step shown at the time?

**Comment by Faugus** [comment]
Proton and Steam Runtime are dealt in parallel.
Having one line the updates will overwrite each other without informing the user if one or the other is done.
