### ISSUE TITLE
Don't highlight the KILL button when the game is not running

### ISSUE THREAD

**Issue by bogdan-the-great** [Faugus/faugus-launcher#16]
The kill button is always highlighted (even when the game wasn't started!). This creates confusion when the game has a long start-up in the background e.g. Deus Ex Mankind Divided. When you don't really know if the game has started or crashed during the start-up process.

Is this even doable? Games can have weird executable names and it runs the game detached in the background (I think).

**Comment by Faugus** [comment]
The kill button is meant to close all games that are running with wine/proton, like a cleanup, not only if a specific game is frozen, but also for any game running in the background and causing problems.
For example, if you are running a game on Steam or Lutris and you press the kill button on Faugus Launcher, those games will be closed as well.

The play button indicates if the game is running or not.

This is not going to change.
Thanks for the feedback.
