### ISSUE TITLE
Use the existing prefix for new game

### ISSUE THREAD

**Issue by bogdan-the-great** [Faugus/faugus-launcher#17]
When I add a new game and select e.g. Lutris' prefix where the game is located, Faugus will create there a new prefix anyway.

![image](https://github.com/user-attachments/assets/348cc74a-8b81-4ec7-843a-3f205eac19e3)
(Faugus' prefix created inside the existing prefix)

Can this be changed? If not - can there be a warning that it won't use any existing prefix (even when selected as directory)?

**Comment by Faugus** [comment]
Thanks for reporting.

It should be fixed now.

Flatpak is updated: https://github.com/Faugus/faugus-launcher/releases/download/v1.1-3/faugus-launcher-0.1.2.flatpak
