### ISSUE TITLE
Semicolons not escaped in games database

### ISSUE THREAD

**Issue by nullref** [Faugus/faugus-launcher#20]
Try adding a game with a semicolon in the title field, the semicolon ends up being saved to games.txt. When reloading the file the text after the semicolon in the title will end up in the path field, and all other fields being offset by one.

**Comment by Faugus** [comment]
Thanks for reporting.
I'll fix it as soon as I can.

**Comment by Faugus** [comment]
Escaping the semicolons was causing too much problem.
So for now I decided to block the user from using semicolons on the entries.
Maybe in the future I'll find a better solution.
