### ISSUE TITLE
how to use gamescope without make shorcut?

### ISSUE THREAD

**Issue by naxil** [Faugus/faugus-launcher#21]
hello how to use gamescope? i use arch with latest faugus-launcher. (how to use dark theme?)

**Comment by Faugus** [comment]
Hello there!

Are you using the Flatpak version?

**Comment by naxil** [comment]
no i have use yay for install faugus-launcher. why i can't update it for 1.14 umu? i have compiled umu-launcher how to update it on faugus? sorry for lot of question but i still on 1 oct version

**Comment by Faugus** [comment]
Dark Theme: It uses the theme of your DE.
If it's not being applied, your system is probably missing some package/setting.

UMU 1.1.4: It uses the [umu-launcher](https://archlinux.org/packages/multilib/x86_64/umu-launcher/) which was updated recently.
Update your system and you should get the 1.1.4 version.

Gamescope:
You can set like this, for a specific prefix:
![image](https://github.com/user-attachments/assets/911ce53c-1be9-4383-81a7-4ca45409ca2f)
Or if you are creating a shortcut from the .exe file:
![image](https://github.com/user-attachments/assets/c211c555-699a-4546-b76e-912692c99fed)
