### ISSUE TITLE
[Feature]: Add an option to disable popup when starting a game.

### ISSUE THREAD

**Issue by CcMenta** [Faugus/faugus-launcher#22]
I don't like it when I start a game the faugus launcher appears it shows that I have the latest version of steam runtime and proton ge (I set it to proton ge from umu) then it close it's self. It would be great if you can either completely disable the popup or only show the popup when it's download/updating something.

**Comment by Faugus** [comment]
Done. Thanks for the feedback.

![image](https://github.com/user-attachments/assets/489856b9-f7ca-432d-8765-a7f0008a2526)
