### ISSUE TITLE
Default Prefix "Faugus Create Shortcut" settings after initial creation

### ISSUE THREAD

**Issue by Hessutar** [Faugus/faugus-launcher#23]
Heya! Great work with this launcher! Really like the simplicity and easiness to use UMU.

One thing I noticed while installing battle.net via the "Faugus Create Shortcut" menutool is that I couldn't find a away to adjust the application/shortcut settings afterwards. I deleted the application/shortcut and created a new one via the menutool with wanted settings.

![image](https://github.com/user-attachments/assets/580badef-6664-4cef-babd-51ab7ca4e0c0)

I noticed this was when I installed Gamemode and Mangohud aftewards and I wanted to enable them to battle.net application/shortcut but couldn't find a way to do it via the GUI. I tried setting them with the Faugus Launcher application default prefix settings but they didn't seem to have affect on applications/shortcuts generated before the default prefix settings were changed. Applications/shortcuts generated via the menutool after changing default prefix settings seemed to affect new applications/shortcuts.

I hope my explanation was clear enough :) 

Keep up the good work!

-Hessutar

**Comment by Faugus** [comment]
Hello there! I'm glad you liked it!. Thanks for the feedback.

Unfortunately, there's no way to edit an already created shortcut that uses the default prefix. You need to recreate it.

These options are only for new shortcuts

![image](https://github.com/user-attachments/assets/abe1f3b1-0d82-43bc-9ee7-bc43d88b49a7)

Or when executing a .exe file directly, like this

![image](https://github.com/user-attachments/assets/1307c283-27fa-422f-940a-5af64d326090)

**Comment by Hessutar** [comment]
Alright, thanks for the info! :)

Then I have a follow up question. To completely remove the old shortcut and application do I need to do anything else than delete the shortcut from my desktop and the application from .local/share/applications?

-Hessutar

**Comment by Faugus** [comment]
Exactly.

**Comment by Hessutar** [comment]
Alright, perfect. Thanks for the info, case closed! :)
