### ISSUE TITLE
Suggestion: Add automatic game launcher installers

### ISSUE THREAD

**Issue by ToRRent1812** [Faugus/faugus-launcher#24]
An idea from user perspective would be simple
You click Add, a new box appears where You choose Add Game or Install Game Launcher
Clicking on install game launcher would show a list of popular game launchers like ubi connect, ea app, EGS, Hoyoapp etc.
User clicks what he wants, the app automatically downloads the app, and starts installation with winetricks/workaround scripts if needed.
I'm not talking about full API integration with the launcher, but just a simple script that would download .exe and starts installation without much hussle.

Similar feature is available in protonplus, lutris and bottles.

**Comment by Faugus** [comment]
Thanks for the suggestion.
I added an automated installation for some game launchers.
I don't know if this is the best approach, but I'll leave like this for now.

![image](https://github.com/user-attachments/assets/4257aeb1-a363-466d-81fc-ba2e87a34ed3)
