### ISSUE TITLE
[Suggestion] Add FPS limiter to tools

### ISSUE THREAD

**Issue by onlyreportingissues** [Faugus/faugus-launcher#27]
I'm using this command in Steam for DXVK games:

DXVK_FRAME_RATE=97

_______

And I'm using this command in Steam for VKD3D-Proton games:

mangohud MANGOHUD_CONFIG=fps_limit=97,no_display                                    

_______

The MangoHud command works for both though, DXVK and VKD3D-Proton. Maybe the default could be to hide the display with the no_display command, but if MangoHud is activated in the tools section also, then the no_display part could be removed from the FPS limit command.

// 97 is the FPS limit I chose

**Comment by Faugus** [comment]
Thanks for the suggestion, but I'm not going to implement that.
The goal is to keep unbloated.

Just put `DXVK_FRAME_RATE=97` or `MANGOHUD_CONFIG=fps_limit=97,no_display` on Launch Arguments.
