### ISSUE TITLE
[Suggestion] Option to display only FPS instead of full MangoHud

### ISSUE THREAD

**Issue by onlyreportingissues** [Faugus/faugus-launcher#28]
Maybe a "FPS only" sub-option could be added below the MangoHud one in the tools section that enables MangoHud, but only to show the FPS and nothing else.

In steam the command is called:

mangohud MANGOHUD_CONFIG=fps_only

**Comment by Faugus** [comment]
Thank for the suggestion, but I'm not going to implement that.
Please enable the MangoHud option and put `MANGOHUD_CONFIG=fps_only` on Launch Arguments or just set the `MangoHud.conf` file.
