### ISSUE TITLE
Game Arguments dont work

### ISSUE THREAD

**Issue by dCo3lh0** [Faugus/faugus-launcher#29]
I've tried using the input for Game arguments for the exe file to launch and it crashes instantly, but if i remove it launches normally but without the config arguments i've wanted.

**Comment by dCo3lh0** [comment]
it looks like this:

`WINEPREFIX=/mnt/Arquivos/Games/Faugus/Prefixes/dungeon-keeper-gold GAMEID=umu-1207658934 PROTONPATH=GE-Proton gamemoderun PROTON_USE_WINED3D=1 gamescope --prefer-vk-device 1002:1638 -w 1920 -h 1080 -W 1920 -H 1080 -r 60 -f --mangoapp "/usr/bin/umu-run" "/mnt/Arquivos/Games/Faugus/Prefixes/dungeon-keeper-gold/drive_c/KeeperFX/keeperfx.exe" "-cd -alex -vidsmooth"`

these quotes "-argument1 -argument2" after the exe may not work i think.

**Comment by Faugus** [comment]
It works. I just tested.
If the game is crashing, maybe it's not accepting the arguments.
Some games use double dash (--) instead of a single dash (-).
Give it a try.

**Comment by dCo3lh0** [comment]
really weird, there is a launcher with pre-configs for the game that you can do, that defines parameters automatically for keeperfx.exe in windows, so i thought that copying would work right, well i've opened the CMD by winetricks gone to the directory and tried to see which parameters did exist for the keeperfx.exe file, it doesn't exist!!! Even if the launcher configured the parameters in a secondary file, really weird, so the problem is on them, sorry i'm gonna close the issue.

**Comment by Faugus** [comment]
But you're actually right!
One argument is working fine.
More than one is not.
I need to separate them with quotes.

**Comment by Faugus** [comment]
I just released an update.
It should be fixed now.
