### ISSUE TITLE
Gamemode not working

### ISSUE THREAD

**Issue by dCo3lh0** [Faugus/faugus-launcher#30]
I've installed the game I'm now playing both on faugus and lutris just for tests sake, on lutris the gamemode works and the game runs ok, of course using wine GE and so forth, but on faugus, when i turn on gamemode, the screen dimming for powersaving before it turns off happens after 5 minutes of gameplay. First it was issuing me of a error with LD_PRELOAD for libgamemodeauto.so.0, so i've set the environment variable `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0` on the Launch arguments and the error disappeared, i've fixed another error of gamemode here with the governor of powersaving, it was a permission issue so i've set `sudo usermod -aG gamemode $USER`, and this other issue from `gamemoded -t` is gone, anyways, it was supposed for the powersaving screendiming not happen, but it keeps happening so gamemode is not working, but its working on lutris.

**Comment by Faugus** [comment]
Could you please test using `LD_PRELOAD=/usr/lib/libgamemode.so.0` as a launch argument?

**Comment by dCo3lh0** [comment]
it wouldn't work because the libs are respectively on `/usr/lib/i386-linux-gnu/libgamemode.so.0` and `/usr/lib/x86_64-linux-gnu/libgamemode.so.0`, so i will choose the x64, lets try.

Edit: It keeps happening, anyways i will only be back here at night tomorrow or after tomorrow.

The environment variable i've setup was `LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libgamemode.so.0:/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0"`

**Comment by dCo3lh0** [comment]
After sleeping a little i thought why not try out in the launch options gamemoderun before gamescope, i'm dumb, gonna try at night.

**Comment by Faugus** [comment]
I can't reproduce on my system.

With gamemode OFF:
```
[faugus@archlinux ~]$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
powersave
```
![image](https://github.com/user-attachments/assets/eb82032c-ca24-4e19-80d4-14f5069f2c9e)

With gamemode ON:
```
[faugus@archlinux ~]$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
```
![image](https://github.com/user-attachments/assets/51cbc57f-0d25-43c5-bb60-4ae1470a0d78)

Setting the LD_PRELOAD environment should be enough.
I'll set it by default on the app.

I also get these error messages, but according to one of the Lutris developers, it doesn't prevent gamemode from functioning properly.
https://github.com/lutris/lutris/issues/5467#issuecomment-2101488414

**Comment by Faugus** [comment]
Lutris also has this option:

![image](https://github.com/user-attachments/assets/8da106d9-1683-49f1-9d91-77ed0496e18d)

Maybe it's this option which is really preventing the screen dimming?

**Comment by dCo3lh0** [comment]
Got a time off here, i'm gonna setup on mangohud to display if gamemode is on or off later, but ler me ask, if i setup environment variables on the launch command before gamescope and the gamemoderun comes before the environment variables, like the variables are in between gamemoderun and gamescope, does the command gives error or not? On lutris the variables come before and gamemoderun gamescope comes later, i will try later at home.

**Comment by dCo3lh0** [comment]
Yeah maybe is this command. Disable screen saver on lutris, may be this same thing can be imported to faugus.

**Comment by Faugus** [comment]
I tried using `gamescope gamemoderun` and `gamemoderun gamescope`.
Both gave the error and both worked fine.

On MangoHud, if you don't set the LD_PRELOAD it will show gamemode off, but it's working.

**Comment by Faugus** [comment]
Well, I usually have the screen saver/dimming off on my system.
I just enabled to test it and it's working fine with feral gamemode.
I've no idea why it's not working on your system.
I'll release a build that automatically apply the LD_PRELOAD envar and hide the error messages to prevent confusion.

**Comment by dCo3lh0** [comment]
I'm back now, i think there is not much i can do about it, because if i change the profile on my processor using what is talked here (https://askubuntu.com/questions/1322492/how-to-set-as-default-performance-mode-on-ubuntu-20-04-instead-of-powersave) i think it will mess with my nvidia-prime setup which is on "on-demand" mode, and this mode from their setup sets the cpu profile on powersave mode, i think i cant setup on performance, only if i deactivate my dual gpu setup, so i can't setup this way, but there is a workaround, as you said, if i deactivate the screen dimming and the monitor turn off mode, on energy configurations here, it will annoy me a little since i will need to suspend or block session manually, but i can deal with it. And looking at lutris it displays gamemode off as well, even if the screen saving is disabled. Well since this is screensaving related, maybe change this to a feature request for a toggle for disabling screen saver?

**Comment by Faugus** [comment]
You don't need to manually set the cpu governor to performance. Gamemode does that automatically.

**Comment by ARKye03** [comment]
Hello, February 4th, 2025, I'm experiencing this issue: `gamemode` won't load, same logs as above. Using LD_PRELOAD didn't fix the error unless I was doing it wrong(I have no idea how it could be wrong). I'm on Arch Linux, Wayland. Console logs this:
```log
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
... # Same thing multiple times
```
I have  both installed:
- gamemode 1.8.2-1
- lib32-gamemode 1.8.2-1

Also:
- lib32-mangohud 0.7.2-1
- mangohud 0.7.2-2

MangoHud works, but it doesn't show `gamemode` as active. What can I do, I'm on a desktop PC, using Nvidia RTX 3050 card.

- Faugus-launcher version: 1.2.11-1
- `gamemode -t` passes all tests
- My user is already in `gamemode` group.
 
If it is worth it, this is the command that I tried to run one of my games:

```sh
LD_PRELOAD=/usr/lib/libgamemode.so.0 WINEPREFIX="/home/archkye/.config/faugus-launcher/prefixes/pokemon-reloaded" GAMEID=pokemon-reloaded PROTONPATH=GE-Proton gamemoderun "/usr/bin/umu-run" "/home/archkye/Games/Reloaded The Last Beta/Proyecto Reloaded The Last Beta 1.6.2.exe"
```

**Comment by Faugus** [comment]
Please don't set the LD_PRELOAD env variable.
I just tested on Arch Linux with a 64bit and a 32bit game, both working fine.
I can't reproduce your issue.

**Comment by ARKye03** [comment]
> Please don't set the LD_PRELOAD env variable. I just tested on Arch Linux with a 64bit and a 32bit game, both working fine. I can't reproduce your issue.

I'm sorry for writing my previous message, this seems more related to `gamemode` itself instead of how Faugus uses it, checking systemctl and gamemoded -s, I can confirm that gamemode seems active, similar to the behaviour explained [here](https://github.com/lutris/lutris/issues/5467). The logs are annoying, because of the amounts of errors, despite the program working "fine" I guess?. Again, my apologies.

**Comment by Faugus** [comment]
No worries.
Enjoy the app :)
