### ISSUE TITLE
[BUG] Gamescope displaying half of the fps the games are using

### ISSUE THREAD

**Issue by dCo3lh0** [Faugus/faugus-launcher#31]
Maybe something changed from version 1.1-20 to 1.1-22, gamescope instead of displaying 60 fps that the game is running on is displaying 30 fps with 33.3ms of screen response.

**Comment by Faugus** [comment]
This is not my bug. I didn't change anything related to that.

**Comment by dCo3lh0** [comment]
definitely my mistake sorry, my mistake.
