### ISSUE TITLE
Add game to faugus launcher when creating shortcut with "Faugus Create Shortcut".

### ISSUE THREAD

**Issue by CcMenta** [Faugus/faugus-launcher#32]
I don't know if it's a feature or a bug that when you use the "Faugus Create Shortcut" script/program it doesn't put the game in to the launcher, it only creates a .desktop file.

**Comment by Faugus** [comment]
Hello there!

That's how it is supposed to work.
Using "Faugus Create Shortcut" will create a shorcut that uses the default prefix.
When using the launcher it will create a separate prefix for each game/app.

**Comment by CcMenta** [comment]
Thanks for the answer I wasn't sure how it should work.
