### ISSUE TITLE
If an instance of a game/program runs can't run anyother game/program until it's closed.

### ISSUE THREAD

**Issue by CcMenta** [Faugus/faugus-launcher#33]
If I run a game/program and want to run a other game/program I need to first close the already running game/program and after that the game/program that I wanted to run will run, but if I tried opening multiple game/program all of them would start running once the first game/program is closed.

**Comment by Faugus** [comment]
Yes. That's how `umu-launcher` works by default.

**Comment by CcMenta** [comment]
Is there a way to change this? I don't think it works correctly because if a game is running and I launch two other games if I close the first game the other two games start running, which shouldn't happen.

**Comment by Faugus** [comment]
umu-launcher has an option to change this.
Last time I tried I had problems with it.
I'll test it again and if I mange to make it work properly, I'll change it.

**Comment by WinterTreat** [comment]
Hi! I was wondering if this was eventually added. I'd like to be able to open multiple games with the same prefix. :p

**Comment by Faugus** [comment]
Not yet.
https://github.com/Open-Wine-Components/umu-launcher/issues/283
