### ISSUE TITLE
Multiple matches of faugus-launcher;1.1-25.fc41;noarch;copr:copr.fedorainfracloud.org:faugus:faugus-launcher

### ISSUE THREAD

**Issue by SAJewers** [Faugus/faugus-launcher#35]
I get this error in KDE Discover whenever Faugus Launcher is updated, preventing all updates.
Updating via dnfdragora or dnf in the terminal works fine, and allows Discover to update all other packages
![Snapshot_2024-12-09_07-54-28](https://github.com/user-attachments/assets/6c92ba89-5899-4e25-b176-0f01aa2e7524)
![Snapshot_2024-12-09_07-58-31](https://github.com/user-attachments/assets/d68f71ad-bb9c-4d59-af72-4800d402059a)

**Comment by Faugus** [comment]
Thanks for reporting that!
It should be fixed now.
I just released a new build.
Please try to update and let me know if it's working properly.
