### ISSUE TITLE
Use run instead of runinprefix proton verb

### ISSUE THREAD

**Issue by CcMenta** [Faugus/faugus-launcher#37]
Modded stardew valley (windows version) didn't wanted to work with `PROTON_VERB=runinprefix` but it works with `PROTON_VERB=run`. I don't know why it works but needs more testing. I [asked](https://github.com/Open-Wine-Components/umu-launcher/issues/307) what is the difference between `run` and `runinprefix` but when I write this I still didn't got an asnwer.

**Comment by Faugus** [comment]
As [R1kaB3rN](https://github.com/R1kaB3rN) said, It can cause issues, so I won't add it.
