### ISSUE TITLE
Incorrect versioning

### ISSUE THREAD

**Issue by AngryPenguinPL** [Faugus/faugus-launcher#38]
I would like to draw attention to a seemingly trivial thing, but which makes packaging in Linux distributions a bit more difficult.

Released versions of applications are named as 1.1-24 and this creates problems especially for .rpm distributions because rpm treats "-" in the package version as an illegal char and this causes us to change the package versions to various other combinations because rpmbuild does not allow to build such a package.
More info here: https://twiki.cern.ch/twiki/bin/view/Main/RPMAndDebVersioning

The best solution would be to adopt sematic versions like this:
1.1 - the main release and .24 - as a maintenance release,
which would look like faugus-launcher-**1.1.24**

What do you think?

**Comment by Faugus** [comment]
Thanks for pointing that! I didn't know about it.

I will change it on the next release.

**Comment by Faugus** [comment]
Do you know if that's what's causing [this problem](https://github.com/Faugus/faugus-launcher/issues/35)?

**Comment by AngryPenguinPL** [comment]
> Do you know if that's what's causing [this problem](https://github.com/Faugus/faugus-launcher/issues/35)?

I'm not 100% sure but I think it might be because you're building the same version of the package twice in copr.

Look:

Build 1: https://download.copr.fedorainfracloud.org/results/faugus/faugus-launcher/fedora-41-x86_64/08364084-faugus-launcher/
Build 2: https://download.copr.fedorainfracloud.org/results/faugus/faugus-launcher/fedora-41-x86_64/08364085-faugus-launcher/

both contain the same version of the package, same release and for the same system.

I think this may confuse pkcon (used by discover), thats why dnf works fine because it should try to pick always latest release.

As solution try build new version of faugus-launcher with changed "release" in spec file. 
In practice, each subsequent re-build of the same version of the package should contain a higher release number. That is, the package built for the first time should have "1", and in the case of a subsequent rebuild "2", etc. and when you release a new version of a package and change the "version" in the spec file, you reset the "release" value to 1.

That's what I think - although I don't know how copr works very well.

**Comment by Faugus** [comment]
I don't know what I am doing wrong.
The rpmbuild command always create the file with the hyphen for the release.

**Comment by Faugus** [comment]
I was looking at other packages and all of them use hyphen to separate the release.
Take the GE's repo as an exemple: https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-41/packages/

I think that info you shared is outdated.

**Comment by AngryPenguinPL** [comment]
Look at flatpak package in GE repo.
![Screenshot_2024-12-11-21-12-09-155_com android chrome](https://github.com/user-attachments/assets/25bd2c95-7180-40fc-a4ab-4c359ec9bbd6)

Every new build comes  with different release number.

**Comment by Faugus** [comment]
Yes, that was my mistake. I already fixed that. I'm talking about the hyphen to separate the release.

**Comment by AngryPenguinPL** [comment]
This hyphen separates version from release. You don't create it manually, otherwise .rpm will consider it an illegal char.

So it looks like this:
version-release
as example
1.1.25-1

and of you need rebuild package because for example it need small patch or need to be rebuild for library soname change ten you change only release number from 1 to 2.
This should fix problems.

**Comment by Faugus** [comment]
Oh I got it now. I'm going to do that from now on. Thanks again.
