### ISSUE TITLE
Small interface game label's wrap when they shouldn't

### ISSUE THREAD

**Issue by CcMenta** [Faugus/faugus-launcher#39]
In small interface game labels should only wrap when there is no more horizontal space, but they making it look odd.
It's looks like this: 
![Screenshot_20241211_164737](https://github.com/user-attachments/assets/a4ff3fba-0ce4-4b07-9a76-03bbb56e9f3e)
but it should look like this:
![Screenshot_20241211_164805](https://github.com/user-attachments/assets/57c251e4-e0de-4399-a893-7982af718108)
The `game_label.set_max_width_chars(1)` is the issue using `game_label.set_max_width_chars(50)` is what I used to take the second screenshot, tested in big interface and wraping works fine.

**Comment by Faugus** [comment]
Thanks for reporting that.
I meant to wrap the label only for the big interface.

**Comment by Faugus** [comment]
Already fixed it.
