### ISSUE TITLE
[IDEA] Possibility do display covers?

### ISSUE THREAD

**Issue by ppogorze** [Faugus/faugus-launcher#4]
It will be nice to display icons and/or covers (like Lutris).
Any plans for that?

**Comment by Faugus** [comment]
I don't plan to implement it.
The goal is to keep it as simple and functional as possible.

**Comment by Faugus** [comment]
@ppogorze I reworked the way icons are extracted from the .exe, which made a lot easier to implement icons on the main screen.

**Comment by Faugus** [comment]
@ppogorze I reworked the way icons are extracted from the .exe, which made a lot easier to implement icons on the main screen.
