### ISSUE TITLE
 Add Support for Using System-Packaged Proton Versions (e.g., Proton-CachyOS or proton-ge-bin )

### ISSUE THREAD

**Issue by structnull** [Faugus/faugus-launcher#41]
It would be beneficial if this app could support using system-packaged Proton versions, such as proton-cachyos. This version of Proton, provided by CachyOS project, includes cherry-picked cpu optimizations and experimental features from Proton Experimental, offering improved performance and functionality.

By allowing users to select a system-installed Proton version, the app could:

1. Leverage system-specific optimizations (e.g., CPU-specific tuning in CachyOS).

2. Stay aligned with user preferences for custom or experimental builds.

3. Reduce redundancy by using a shared Proton installation.

Reference: https://wiki.cachyos.org/configuration/gaming/#proton-cachyos

**Comment by Faugus** [comment]
Hello there.

I'll think about it.

For now, if you want to use them, you can symlink the folders to user local:
```
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos ~/.local/share/Steam/compatibilitytools.d/
ln -s /usr/share/steam/compatibilitytools.d/proton-ge-custom ~/.local/share/Steam/compatibilitytools.d/
```
And put `UMU_NO_RUNTIME=1` on Launch Arguments.

**Comment by Faugus** [comment]
I added support for proton-cachyos and proton-ge-custom.
But you still need to symlink them to `~/.local/share/Steam/compatibilitytools.d/` cause umu-launcher doesn't read Proton builds installed in `/usr/share/steam/compatibilitytools.d/`.
You won't need to add `UMU_NO_RUNTIME=1` anymore.
