### ISSUE TITLE
Feature request: support for gamescope

### ISSUE THREAD

**Issue by structnull** [Faugus/faugus-launcher#42]
I would like to request built-in support for [[Gamescope](https://github.com/Plagman/gamescope)], similar to how MangoHud is integrated into the app. This feature could work akin to the implementation in tools like Bottles or lutris , where users can easily enable and customize Gamescope with various options directly within the application interface.  

**Key Features:**  
- **Toggle Gamescope:** A simple switch or checkbox to enable/disable Gamescope.  
- **Customizable Options:** Provide a user-friendly way to set common Gamescope options (e.g., resolution, refresh rate, scaling, and performance settings).  
- **Command-line Override:** Allow users to manually add custom Gamescope arguments if desired.  
- **Compatibility Check:** Ensure the feature only appears if Gamescope is installed on the user's system.  

This integration would greatly enhance the usability for users who prefer leveraging Gamescope's features to improve their gaming experience like adaptive sync or hdr . Thank you for your work in this launcher!

**Comment by Faugus** [comment]
The problem is that I couldn't make gamescope work with Flatpak, so I won't add it for now.
