### ISSUE TITLE
Debian 12 dependencies (gir1.2-appindicator3-0.1)

### ISSUE THREAD

**Issue by ladimau** [Faugus/faugus-launcher#43]
Package gir1.2-appindicator3-0.1 is not available in debian 12 repos, making faugus-launcher not possbile to install. I'm not familiar with the process of fixing such issues, so let me know what my options are, and whether it's something reasonable or easy for the developer to fix. Localsend, for example, fixes this issue by using an alternative dependency : "gir1.2-ayatanaappindicator3-0.1" which is available in debian repos

**Comment by Faugus** [comment]
Thanks for reporting.
I already fixed and it will be available on the next release.

**Comment by Faugus** [comment]
It should be fixed now.
Could you please update and tell me if it's working for you?
