### ISSUE TITLE
QOL Suggestion: Open prefix folder in right click menu

### ISSUE THREAD

**Issue by ToRRent1812** [Faugus/faugus-launcher#45]
It would be nice to have an option on right click menu that opens file manager at prefix location.
![Zrzut ekranu_20241218_012542](https://github.com/user-attachments/assets/d4bf912d-fb87-4ec7-84e4-52a3c784cf4b)

**Comment by Faugus** [comment]
Thanks for the suggestion.
I just added the option.
Please update Faugus Launcher.
