### ISSUE TITLE
Ok button not works. Pictures of games disappear

### ISSUE THREAD

**Issue by naxil** [Faugus/faugus-launcher#46]
like title. i try to add or change some inside games list and ok not works at all, only cancel works after edit and game pic disappear.
I can use OK like "accept change" and need to close every window with X.

CPU: 6-core AMD Ryzen 5 5600G with Radeon Graphics (-MT MCP-)
speed/min/max: 400/400/4464 MHz Kernel: 6.12.4-zen1-1-zen x86_64 Up: 19m
Mem: 3.17/31.24 GiB (10.2%) Storage: 5 TiB (24.1% used) Procs: 323
Shell: Bash 5.2.37 inxi: 3.3.36

faugus version from arch aur : r281.ded77e9-1

**Comment by Faugus** [comment]
Thanks for reporting!
Last updates broke it.
I already fixed it.
Please update Faugus Launcher.

**Comment by naxil** [comment]
how i can update it on arch? i need to update only via aur? i havent understood the "noarch" rpm

**Comment by Faugus** [comment]
Did you installed it using `yay`?

If yes, just type `yay` in your terminal.

**Comment by ultradev-coder** [comment]
is the fix out for the .deb package?

**Comment by Faugus** [comment]
Not yet

**Comment by Faugus** [comment]
It should be fixed now @ultradev-coder @naxil

**Comment by ultradev-coder** [comment]
thanks
