### ISSUE TITLE
20-25% cpu usage on python process

### ISSUE THREAD

**Issue by ultradev-coder** [Faugus/faugus-launcher#47]
hi, i have noticed that python3 for some reason uses a significant amount of cpu, but this doesn't happen on other launchers that use umu-launcher so i think this is probably a faugus launcher issue or umu-launcher acting weird.
im using linux mint 22.
![image](https://github.com/user-attachments/assets/1ee0a491-f1ea-4fc6-a055-5e18af58fba2)

**Comment by Faugus** [comment]
Thanks for reporting. I'll take a look.

**Comment by Faugus** [comment]
It should be fixed now.

**Comment by ultradev-coder** [comment]
thanks for fixing it!
