### ISSUE TITLE
Can't install Faugus Launcher on Nobara

### ISSUE THREAD

**Issue by SneakiestDuke68** [Faugus/faugus-launcher#49]
Hello, i have problem to install Faugus on Nobara.
"sudo dnf -y copr enable faugus/faugus-launcher" and error that not found chroot in project Copr (nobara-41-x86_64)
"sudo dnf -y install faugus-launcher" and error can't match  argument: faugus-launcher
![Zrzut ekranu_20241219_201046](https://github.com/user-attachments/assets/728e4626-c4d6-4b48-a0c4-762d07a9e7a5)
![Zrzut ekranu_20241219_201305](https://github.com/user-attachments/assets/cbccb47a-8158-4885-beeb-3b8a66785bce)

**Comment by Faugus** [comment]
I just fresh installed Nobara 40 on a VM and installed Faugus Launcher just fine.
There's something wrong with your system.

![nobara](https://github.com/user-attachments/assets/39063fa7-397f-4bd3-bae0-82e1d0919844)

**Comment by SneakiestDuke68** [comment]
I'm just upgrade to Nobara 41 and i see there no python3-pynput fc41 to download actually. The rest of packages on your screen i have just only this one.

**Comment by Faugus** [comment]
`pynput` is in my repo.
https://copr.fedorainfracloud.org/coprs/faugus/faugus-launcher/package/python-pynput/

**Comment by SneakiestDuke68** [comment]
I got it by "sudo dnf -y copr enable faugus/faugus-launcher fedora-41-x86_64" and launcher works now, games also :)
Only problem what i have prefix folder works only in home directory (/home/sneakiestduke68/.config/faugus-launcher/prefixes/). When i set new path for prefixes on second ssd, game not finding prefix folder. I need set additional permissions for launcher ?

**Comment by Faugus** [comment]
Does the new prefix location have spaces?
Something like `/mnt/ssd/windows games/`
If there is, it's a bug that I've already fixed.
I'll push to Fedora's repo right now.

**Comment by SneakiestDuke68** [comment]
It looks like: "/run/media/sneakiestduke68/Gry linux/Faugus/" .

**Comment by Faugus** [comment]
Yes. There's a space between Gry and linux.
I already pushed the fix for the Fedora' repo.
Please update it.

**Comment by SneakiestDuke68** [comment]
Now everything is working. Thanks a lot :)
Your launcher is really nice and minimalistic.

**Comment by Faugus** [comment]
Thanks! I'm glad you like it.
