### ISSUE TITLE
Runner selection not working

### ISSUE THREAD

**Issue by Benjo-am-Banjo** [Faugus/faugus-launcher#5]
Hello Faugus,

I really like your minimalistic launcher!
But i think since the latest update there happend something with the runner selection.
I have different versions of wine / proton in the compatibilitytools.d folder. But when i want to select a specific version in the Launcher i can only select "GE-Proton Latest (default)" or "UMU-Proton Latest". See attached screenshot.

I'm using Nobara 40 as my distro with Gnome on Wayland.

Was this a intended change or is it a bug?

Best regards,
Benjo-am-Banjo

![faugus-launcher-no-runner-selection](https://github.com/user-attachments/assets/52d822d7-8d87-4672-85bf-b1ac55e03e90)

**Comment by Faugus** [comment]
Thanks for reporting.
It should be fixed now.
Please update and let me know.

**Comment by Benjo-am-Banjo** [comment]
Thank your very much. It's working now.
