### ISSUE TITLE
prefix crash

### ISSUE THREAD

**Issue by ultradev-coder** [Faugus/faugus-launcher#50]
if i try to put a folder with spaces in its name (like home/user/prefixes/Windows Game), faugus launcher crashes. this doesn't happen if i use a folder with no spaces or if i put a quotation mark (like "home/user/prefixes/Windows Game")

**Comment by Faugus** [comment]
Thanks for reporting.
It should be fixed now.
Please update Faugus Launcher.

**Comment by ultradev-coder** [comment]
Thanks for fixing
