### ISSUE TITLE
Bug: can't delete a prefix

### ISSUE THREAD

**Issue by ToRRent1812** [Faugus/faugus-launcher#53]
I have a bug where clicking del does nothing, so I manually removed the prefix and now faugus still shows I have a game in non-existent folder. Clicking delete on a prefix again gives me this in terminal:

`Traceback (most recent call last):
  File "/usr/bin/faugus-launcher", line 684, in on_context_menu_delete
    self.on_button_delete_clicked(selected_item)
  File "/usr/bin/faugus-launcher", line 1548, in on_button_delete_clicked
    confirmation_dialog = ConfirmationDialog(self, title, game.prefix)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/faugus-launcher", line 3257, in __init__
    subprocess.Popen(["canberra-gtk-play", "-i", "dialog-warning"])
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: 'canberra-gtk-play'
`

As a workaround, I reached to .config/faugus-launcher and removed entry in games.json and latest-games.txt

I manually compiled the app for OpenSuse in [obs](https://build.opensuse.org/projects/home:Rabbit95/packages/faugus-launcher/files/faugus-launcher.spec?expand=1)

**Comment by Faugus** [comment]
I don't support openSUSE. You are on your own.

You could to try to install something like `canberra-gtk-play`, `libcanberra-gtk3-module` or `libcanberra-gtk-module-common` and see if it satisfy the dependency missing.

**Comment by Faugus** [comment]
I was looking at your .spec and I would like to point some things:

- I'm not using `AppIndicator3` anymore. I'm using `AyatanaAppIndicator3`. You will probably have issues if you enable the system tray icon.
- Winetricks is built in umu-launcher, so you don't need to put it as a recommended dependency.

**Comment by ToRRent1812** [comment]
Ok, thanks for the help :D

**Comment by Faugus** [comment]
Thanks for packaging the app!
I'll install openSUSE in a VM and test it.

**Comment by Faugus** [comment]
`typelib-1_0-AppIndicator3-0_1` this is the package you need.

**Comment by Faugus** [comment]
```
Requires:       libappindicator-gtk3
Requires:       libappindicator-gtk3
```

is not used anymore.

**Comment by ToRRent1812** [comment]
updated .spec

**Comment by Faugus** [comment]
I linked you the wrong package, sorry.
The correct one is `typelib-1_0-AyatanaAppIndicator3-0_1`

**Comment by Faugus** [comment]
Looks good now. I just installed in a VM and it's working fine.
Do you plan on keeping it up to date?

**Comment by ToRRent1812** [comment]
Yes, I use tumbleweed for 2 years with no plans to switch. So far I push new build few hours after release.

**Comment by Faugus** [comment]
Do you mind if I put the instructions on the README to install using your repo ?

**Comment by ToRRent1812** [comment]
Feel free to add it.

**Comment by Faugus** [comment]
@ToRRent1812 Hello there!
On the latest release, I added the file [faugus-notification.ogg](https://github.com/Faugus/faugus-launcher/blob/main/assets/faugus-notification.ogg) and `python3-vdf` as a dependency.
You need to update the .spec or the app will be broken.

**Comment by ToRRent1812** [comment]
oops, fixed.

**Comment by Faugus** [comment]
faugus-notification.ogg is inside the folder assets

assets/faugus-notification.ogg

Thank you.

**Comment by ToRRent1812** [comment]
I took the path from fedora src, so I assume this also needs a fix?

**Comment by Faugus** [comment]
The Fedora .spec is correct cause I'm using local files to build.

**Comment by Faugus** [comment]
Hello there.
The new build needs `python3-psutil` as dependency

**Comment by Faugus** [comment]
@ToRRent1812 Hey Łukasz.
There were some updates to the .py files due to the python packaging.
Files were renamed from `-` to `_` :
`faugus-launcher.py` -> `faugus_launcher.py`
`faugus-proton-manager.py` -> `faugus_proton_manager.py`
`faugus-run.py` -> `faugus_run.py`
`faugus-gamepad.py` -> `faugus_gamepad.py`
