### ISSUE TITLE
Winetricks on older GE-Proton version

### ISSUE THREAD

**Issue by SneakiestDuke68** [Faugus/faugus-launcher#54]
Hello again :)
I get small problem with launcher, it can't open winetricks on older GE-Proton version (GE-Proton8-32). On GE-Proton Latest winetricks open normally.
![Zrzut ekranu_20241225_124225](https://github.com/user-attachments/assets/c7fac791-9635-4aed-8bb3-f2fe97b161cd)

**Comment by Faugus** [comment]
Thanks for reporting.
I can't reproduce this error message you are getting.
But running this command directly on the terminal
```
WINEPREFIX="/home/faugus/.config/faugus-launcher/prefixes/faugus" GAMEID=winetricks-gui STORE=none PROTONPATH=GE-Proton8-32 "/usr/bin/umu-run" ""
```
Winetricks doesn't work as well.
So it's a problem with `umu-launcher` and unfortunately I can't do anything about it.
