### ISSUE TITLE
AUR packaging.

### ISSUE THREAD

**Issue by patlefort** [Faugus/faugus-launcher#57]
I am assuming you are supporting the `faugus-launcher-git` package in the AUR. Can you please follow the [guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines#Publishing_new_package_content). A package pulling from the latest git commit shouldn't get mere pkgver bumps. Only if the package itself need changes. There is a comment about it but no response. Also, in the latest bumps, the .SRCINFO file wasn't updated. To be clear, your package will always pull the latest commit when the user build it as the source doesn't specify a tag/branch/commit.

For regular pkgver bump, a package `faugus-launcher` should be created which pull the intended version.

**Comment by Faugus** [comment]
Thanks for the heads up.
But for the users that already has the package installed, is there a way for them to get the updates?
The latest pulls were for a important bug fix and I thought that was the correct way to do it.

**Comment by patlefort** [comment]
That's on them to update it themselves and to follow its development, if they choose to use a -git package. If they want regular update managed by you, you should create a `faugus-launcher` package with regular bumps. The intent behind the `-git` postfix is that it will pull whatever is the latest commit from a git repo. Usually reserved for development and not for "stable" releases.

**Comment by Faugus** [comment]
Got it. Thank you very much.
