### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by Wektory** [Faugus/faugus-launcher#6]
Hi, I wanted to try your launcher, but it didn't do nothing for me, if I tried to start a Battle.net-Setup.exe.
The launcher work if I start it byself.
What I found out the "GE-Proton Manager" is not work cause if I click it the "Default Runner" auto selects the Ge-Proton Latest option and I get a error in terminal: usr/bin/python3: can't open file '/usr/bin/faugus-proton-manager': [Errno 2] No such file or directory.
Can you help me please?
I only installed steam app for the runners (btw I don't use and play on steam) and until now I have used Lutris.
I use ArcoLinux (arch base).

I forgot, my guess there is something with the umu launcher but I don' know how its working, thanks if you feedback.

**Comment by Wektory** [comment]
I forgot, my guess there is something with the umu launcher but I don' know how its working, thanks if you feedback.

**Comment by Faugus** [comment]
Thanks for reporting.

> if I tried to start a Battle.net-Setup.exe

You mean running the .exe file in your file manager?
Open your terminal and run `faugus-launcher`. Try to run something and paste the logs here please.

GE-Proton Manager should be fixed now. Please update and let me know.

**Comment by Wektory** [comment]
I mean I tried to run the exe file with your launcher and I cant install because for the above reasons.
Now I tried to run WoW-cata(installed by  lutris) with the launcher:

WINEPREFIX=/home/wyktor/.config/faugus-launcher/prefixes GAMEID=wow PROTONPATH=GE-Proton9-15 "/usr/bin/umu-run" "/mnt/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft/World of Warcraft Launcher.exe"
WINEPREFIX=/home/wyktor/.config/faugus-launcher/prefixes GAMEID=wow PROTONPATH=GE-Proton9-15 "/usr/bin/umu-run" "/mnt/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft/World of Warcraft Launcher.exe"
WARNING: '/home/wyktor/.local/share/umu/umu_version.json' is obsolete
WARNING: '/home/wyktor/.local/share/umu/reaper' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_dl_util.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_plugins.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_util.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_log.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_consts.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/umu_run.py' is obsolete
WARNING: '/home/wyktor/.local/share/umu/sniper_platform_0.20240125.75305' is obsolete
steamrt is up to date
pressure-vessel-wrap[73104]: W: /home/wyktor/.local/share/umu/var/tmp-LHAPV2/bin does not exist, this probably won't work
pressure-vessel-wrap[73104]: W: /home/wyktor/.local/share/umu/var/tmp-LHAPV2/etc does not exist, this probably won't work
pressure-vessel-wrap[73104]: W: /home/wyktor/.local/share/umu/var/tmp-LHAPV2/lib does not exist, this probably won't work
pressure-vessel-wrap[73104]: W: /home/wyktor/.local/share/umu/var/tmp-LHAPV2/sbin does not exist, this probably won't work
pressure-vessel-wrap[73104]: E: None of the supported CPU architectures are common to the graphics provider and the container (tried: x86_64-linux-gnu, i386-linux-gnu)

GE-Proton Manager has not changed for me.

**Comment by Faugus** [comment]
Could you please delete or rename the folder `/home/wyktor/.local/share/umu/` and try again?
I think the lastest umu update is conflicting with the old one.

> GE-Proton Manager has not changed for me.

Did you update faugus-launcher?

**Comment by Wektory** [comment]
Nice, I deleted the umu folder and now battlenet has already started, thanks.
But the GE-Proton Manager has the same issue, I updated the whole system.
What should I do?

**Comment by Faugus** [comment]
Put `pacman -Q faugus-launcher-git` in your terminal and tell me what version you have.
It should be `r153.9603be9-1`.

**Comment by Wektory** [comment]
Yes, this is what I have too.

**Comment by Faugus** [comment]
Ok. Please run `faugus-launcher` in your terminal, click the GE-Proton Manager button and paste here the logs.

**Comment by Wektory** [comment]
Thats it:
/usr/bin/python3: can't open file '/usr/bin/faugus-proton-manager': [Errno 2] No such file or directory

**Comment by Faugus** [comment]
That's wierd.
I updated the PKGBUILD, so it should be installing the faugus-proton-manager correctly.
Could you please reinstall it as a clean build?
`yay -S faugus-launcher-git --answerclean All --noconfirm`

**Comment by Wektory** [comment]
Done, but nothing changed.
I can use latest UMU-Proton and GE-Proton too with WoW, so the manager is not so important for me.
If I understand correctly the faugus-proton-manager cannot be installed at my place some reason?

**Comment by Faugus** [comment]
Yes. It should copy the faugus-proton-manager file in your /usr/bin/ folder.

You could try to remove the package and reinstall it again.
```
yay -Rns faugus-launcher-git --noconfirm
yay -S faugus-launcher-git --answerclean All --noconfirm
```

**Comment by Wektory** [comment]
Done again, but the faugus-proton-manager is nowhere. 
I can deal without the f-p-m :D, anyways thanks again the helping, at least battlenet games work well with your launcher.
I guess the problem is my system somewhere, but if You have any more ideas I can check if you want.

**Comment by Faugus** [comment]
Thanks for reporting and testing.
I hope you enjoy the app.
