### ISSUE TITLE
runner selection gets reset

### ISSUE THREAD

**Issue by l2nkxk8z** [Faugus/faugus-launcher#8]
runner selection doesn't get remembered, if I select UMU and press OK then try editing again if I open the options it's set to the proton again and I have to change it to UMU again if I want to change any settings.

**Comment by Faugus** [comment]
Thanks for reporting.

It should be fixed now.

Please update and let me know.

**Comment by l2nkxk8z** [comment]
Yeah, it does seem to be fixed. thanks.
